# Info
site_name: SLADE Scripting Documentation
repo_url: https://github.com/sirjuddington/SLADE
edit_uri: ''

# Settings
docs_dir: './mkdocs'
site_dir: './build'
use_directory_urls: false

# Theme
theme:
  name: material
  palette:
    primary: indigo
    accent: amber
    scheme: slate
  favicon: img/favicon.ico
  logo: img/favicon.ico
extra_css:
- 'css/slade-material-dark.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: false

# Documentation Pages
nav:
- Home: index.md
- Examples:
  - Archvile Madness: 'md/Examples/ArchvileMadness.md'
  - Change Textures: 'md/Examples/ChangeTextures.md'
  - Find Text In Entries: 'md/Examples/FindTextInEntries.md'
  - Open Archive: 'md/Examples/OpenArchive.md'
- Namespaces:
  - App: 'md/Namespaces/App.md'
  - Archives: 'md/Namespaces/Archives.md'
  - Game: 'md/Namespaces/Game.md'
  - Graphics: 'md/Namespaces/Graphics.md'
  - UI: 'md/Namespaces/UI.md'
- Types:
  - Archive:
    - Archive: 'md/Types/Archive/Archive.md'
    - ArchiveDir: 'md/Types/Archive/ArchiveDir.md'
    - ArchiveEntry: 'md/Types/Archive/ArchiveEntry.md'
    - ArchiveFormat: 'md/Types/Archive/ArchiveFormat.md'
    - ArchiveSearchOptions: 'md/Types/Archive/ArchiveSearchOptions.md'
    - EntryType: 'md/Types/Archive/EntryType.md'
  - Colour Translation:
    - Translation: 'md/Types/Translation/Translation.md'
    - TransRange: 'md/Types/Translation/TransRange.md'
    - TransRangePalette: 'md/Types/Translation/TransRangePalette.md'
    - TransRangeColour: 'md/Types/Translation/TransRangeColour.md'
    - TransRangeDesat: 'md/Types/Translation/TransRangeDesat.md'
    - TransRangeBlend: 'md/Types/Translation/TransRangeBlend.md'
    - TransRangeTint: 'md/Types/Translation/TransRangeTint.md'
    - TransRangeSpecial: 'md/Types/Translation/TransRangeSpecial.md'
  - Composite Textures:
    - CTexture: 'md/Types/CTexture/CTexture.md'
    - CTPatch: 'md/Types/CTexture/CTPatch.md'
    - CTPatchEx: 'md/Types/CTexture/CTPatchEx.md'
    - PatchTable: 'md/Types/CTexture/PatchTable.md'
    - TextureXList: 'md/Types/CTexture/TextureXList.md'
  - Game:
    - ThingType: 'md/Types/Game/ThingType.md'
  - Graphics:
    - Image: 'md/Types/Graphics/Image.md'
    - ImageConvertOptions: 'md/Types/Graphics/ImageConvertOptions.md'
    - ImageDrawOptions: 'md/Types/Graphics/ImageDrawOptions.md'
    - ImageFormat: 'md/Types/Graphics/ImageFormat.md'
    - Palette: 'md/Types/Graphics/Palette.md'
  - Map Editor:
    - Map: 'md/Types/Map/Map.md'
    - MapEditor: 'md/Types/Map/MapEditor.md'
    - MapLine: 'md/Types/Map/MapLine.md'
    - MapObject: 'md/Types/Map/MapObject.md'
    - MapSector: 'md/Types/Map/MapSector.md'
    - MapSide: 'md/Types/Map/MapSide.md'
    - MapThing: 'md/Types/Map/MapThing.md'
    - MapVertex: 'md/Types/Map/MapVertex.md'
  - General:
    - Colour: 'md/Types/Colour.md'
    - DataBlock: 'md/Types/DataBlock.md'
    - Plane: 'md/Types/Plane.md'
    - Point: 'md/Types/Point.md'
