# Info
site_name: SLADE Scripting Documentation
repo_url: https://github.com/sirjuddington/SLADE
edit_uri: ''

# Settings
docs_dir: 'mkdocs'
site_dir: 'build'
use_directory_urls: false

# Theme
theme: material
extra_css:
- 'css/slade-material.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite

# Documentation Pages
pages:
- Home: index.md
- Examples:
  - Archvile Madness: 'md/Examples/ArchvileMadness.md'
  - Change Textures: 'md/Examples/ChangeTextures.md'
  - Find Text In Entries: 'md/Examples/FindTextInEntries.md'
  - Open Archive: 'md/Examples/OpenArchive.md'
- Namespaces:
  - App: 'md/Namespaces/App.md'
  - Archives: 'md/Namespaces/Archives.md'
  - Game: 'md/Namespaces/Game.md'
  - SplashWindow: 'md/Namespaces/SplashWindow.md'
- Types:
  - Archive:
    - Archive: 'md/Types/Archive.md'
    - ArchiveDir: 'md/Types/ArchiveDir.md'
    - ArchiveEntry: 'md/Types/ArchiveEntry.md'
    - ArchiveFormat: 'md/Types/ArchiveFormat.md'
    - ArchiveSearchOptions: 'md/Types/ArchiveSearchOptions.md'
    - EntryType: 'md/Types/EntryType.md'
  - Game:
    - ThingType: 'md/Types/ThingType.md'
  - Map Editor:
    - Map: 'md/Types/Map.md'
    - MapEditor: 'md/Types/MapEditor.md'
    - MapLine: 'md/Types/MapLine.md'
    - MapObject: 'md/Types/MapObject.md'
    - MapSector: 'md/Types/MapSector.md'
    - MapSide: 'md/Types/MapSide.md'
    - MapThing: 'md/Types/MapThing.md'
    - MapVertex: 'md/Types/MapVertex.md'
  - General:
    - Colour: 'md/Types/Colour.md'
    - Plane: 'md/Types/Plane.md'
    - Point: 'md/Types/Point.md'
